# Generated by Django 6.0.2 on 2026-03-02 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_status_deliveryagent_deliveryassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.deliveryagent'),
        ),
    ]
